version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/macar-x/cashlenx-server"
  dependencies_vendored = true

[[code_formatters]]
name = "gofumpt"
